config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get '/signup',    to: 'users#new'
  post '/signup',   to: 'users#create'
  get '/edit',      to: 'users#edit'
  patch '/edit',    to: 'users#update'
  get '/users',    to: 'users#index'
  patch '/users',    to: 'users#fp_update'
  get '/login',     to:'sessions#new'
  post '/login',    to:'sessions#create'
  delete '/logout', to:'sessions#destroy'
  get '/fp-signup', to: 'users#fp_new'
  get '/timesettings', to: 'time_settings#edit'
  patch '/timesettings', to: 'time_settings#update'
  resources :reserves, only: [:index, :create]
  resources :consultants
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/consultant.rb
class Consultant < ApplicationRecord
  belongs_to :fp_user, class_name: "User"
  belongs_to :user, required: false
  belongs_to :reserve
  validates :fp_user_id, presence: true
  validates :reserve_id, presence: true
end

app/models/reserve.rb
class Reserve < ApplicationRecord
  has_many :consultants, dependent: :destroy
  #has_many :users, :through => :consultants
  has_many :fp_users, through: :consultants,  source: :fp_user
  has_many :users, through: :consultants
end

app/models/time_setting.rb
class TimeSetting < ApplicationRecord
  def self.set(day)
    set_date = Reserve.where(date: day)
    if set_date.empty?
      set = TimeSetting.find_by(week: day.wday.to_i)

      return nil unless set.workday

      set_end = set.start
      while set_end < set.end
        Reserve.create!(date: day, start: set_end, end: set_end += set.interval * 60)
      end
      set_date = Reserve.where(date: day)
    end
    set_date
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: {maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 255}, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  has_many :fp_consultants, class_name:  "Consultant",
                                foreign_key: "fp_user_id",
                                dependent:   :destroy
  has_many :consultant
  has_many :fp_reserves, through: :fp_consultants,  source: :reserve
  has_many :reserve, through: :consultant
  accepts_nested_attributes_for :fp_consultants, allow_destroy: true
  #has_many :following, through: :active_relationships,  source: :followed
  #has_many :followers, through: :passive_relationships, source: :follower
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper

  private
    def logged_in_fp_user
      unless fp_user?
        flash[:danger] = "Please log in."
        redirect_to root_url
      end
    end

    def logged_in_user
      unless logged_in?
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end
end

app/controllers/consultants_controller.rb
class ConsultantsController < ApplicationController
  before_action :logged_in_user
  def index
    @consultants = Reserve.where('date >= ?', Date.current).joins(:consultants).includes(:consultants).where(consultants: {user_id: nil}).order("date").order("start")
  end

  def show
    @consultant = Consultant.where(user_id: nil).find_by(reserve_id: params[:id])
    @reserve = @consultant.reserve
  end

  def update
    consultant = Consultant.find(params[:id])
    consultant.user_id = current_user.id
    if consultant.save!
      flash[:alert] = "予約が完了しました!!"
      redirect_to root_path
    else
      flash[:alert] = "すでに他の人に予約された可能性があります。違う日を選択してください"
      render index
    end
  end

  def destroy
    cos = current_user.consultant.find_by(reserve_id: params[:id])
    cos.user_id = nil
    if cos.save
      flash[:alert] = "キャンセルが完了しました"
    else
      flash[:alert] = "キャンセルが失敗しました"
    end
    redirect_to root_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    if logged_in?
      @user = current_user
      @consultant = @user.reserve.order(:date).order(:start)
      if @user.fp
        @fp_consultants = @user.fp_reserves.where.not(consultants: {user_id: nil}).order("date").order("start")
      end
    end
  end
end

app/controllers/reserves_controller.rb
class ReservesController < ApplicationController
  before_action :logged_in_fp_user
  before_action :set_up

  def index
  end

  def create
    reserve_id_range = reserve_params[:id_set].split(" ")

    fp_reserve = @fp_user.fp_consultants.where(reserve_id: reserve_id_range[0]..reserve_id_range[1])
    fp_reserve.each do |res|
      if !reserve_params[:fp_reserf_ids].include?(res.reserve_id.to_s)
        if res.user_id.nil?
          res.destroy
        else
          flash[:danger] = "#{Reserve.find(res.reserve_id).start.strftime('%H:%M')}開始は予約済の時間です"
        end
      end
    end
    reserve_params[:fp_reserf_ids].each do |res_id|
      if fp_reserve.where(reserve_id: res_id).empty?
        @fp_user.fp_consultants.create!(reserve_id: res_id) unless res_id.empty?
      end
    end
    render 'index'
  end

  private
    def reserve_params
      params.require(:user).permit(:id_set, {fp_reserf_ids: []})
    end

    def set_up
      @day = params[:date] ? Date.parse(params[:date]) : Date.current
      if @day < Date.current
        @day = Date.current
        flash[:alert] = "過去の日付は選択できません"
      end
      @set_time = TimeSetting.set(@day)
      @fp_user = current_user
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email])
    if user
      log_in user
      redirect_to root_path
    else
      flash.now[:danger] = 'E-mailアドレスが登録されていません。もう一度登録したE-mailアドレスかご確認ください'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end

end

app/controllers/time_settings_controller.rb
class TimeSettingsController < ApplicationController
  def edit
    @time_settings = TimeSetting.all
  end

  def update
    setting_params.keys.each do |id|
      set = TimeSetting.find(id)
      set.update_attributes(setting_params[id])
    end
    @time_settings = TimeSetting.all
    render 'edit'
  end

  private
    def setting_params
      params.permit(setting: [:interval, :start, :end, :workday])[:setting]
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update]
  before_action :fp_user,     only: [:index, :fp_update]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_params)
      flash[:alert] = "更新されました。"
      redirect_to root_url
    else
      render 'edit'
    end
  end

  def fp_update
    @user = User.find_by(email: params[:user][:email])
    if @user.update(fp_user_params)
      flash[:alert] = "更新されました。"
      redirect_to users_path
    else
      flash[:alert] = "更新に失敗しました。"
      redirect_to users_path
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :email)
    end

    def fp_user_params
      params.require(:user).permit(:name, :email, :fp)
    end

    def fp_user
      redirect_to(root_url) unless current_user.fp?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/consultants_helper.rb
module ConsultantsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reserves_helper.rb
module ReservesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def fp_user?
    if current_user.nil?
      false
    else
      current_user.fp
    end
  end

  def current_user?(user)
    user == current_user
  end

end

app/helpers/time_settings_helper.rb
module TimeSettingsHelper
  def week(week_number)
    %w(日 月 火 水 木 金 土)[week_number]
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/consultants/index.html.erb
<% tmp_date = nil %>
<% @consultants.each do |reserve| %>
  <% unless tmp_date == reserve.date.to_date %>
    <h3><%= reserve.date.to_date.to_s %></h3>
  <% end %>
  <% tmp_date = reserve.date.to_date %>
  <%= link_to("予約する", consultant_path(reserve.id)) %>
  <%= reserve.start.strftime('%H:%M') %> - <%= reserve.end.strftime('%H:%M') %><br>
<% end %>

app/views/consultants/show.html.erb
<%= form_for @consultant do %>
  <h2><%= @reserve.date.to_date %></h2>
  <h3><%= @reserve.start.strftime('%H:%M') %> - <%= @reserve.end.strftime('%H:%M') %></h3>
  <%= submit_tag "予約を確定する" %>
<% end %>

app/views/layouts/_header.html.erb
<header>
  <%= link_to "FP 相談所", root_path, id: "logo" %>
  <ul>
    <li><%= link_to "Home", root_path %></li>
    <% if logged_in? %>
    <li><%= link_to "ユーザー情報編集", edit_path %></li>
    <li><%= link_to "Log out", logout_path, method: :delete %></li>
    <% else %>
    <li><%= link_to "Log in", login_path %></li>
    <% end %>
  </ul>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ConsultantFp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/pages/_fp_user_logged_in.html.erb
<h2>For Financial Planner</h2>
<h1>ようこそ <%= @user.name %> 様</h1>

<%= link_to "受付可能時間を選択する", reserves_path %><br>
<%= link_to "曜日可能日を設定する", timesettings_path %><br>
<%= link_to "ユーザー一覧を設定する", users_path %><br>

<h4> 予約一覧 </h4>
<% @fp_consultants.each do |cos| %>
  <%= cos.date.to_date %>
  <%= cos.start.strftime('%H:%M') %> - <%= cos.end.strftime('%H:%M') %>
  <%= cos.users.first.name %>樣が予約済<br>
<% end %>

app/views/pages/_user_logged_in.html.erb
<h1>ようこそ <%= @user.name %> 様</h1>

<%= link_to "ファイナンシャルプランナーへの相談を予約する", consultants_path %>

<h3>確定済みの予約</h3>
<h3><%= "#{@consultant.size}件の予約をしています。" %></h3>
<% @consultant.each do |cos| %>
  <%= cos.date.to_date %>
  <%= cos.start.strftime('%H:%M') %> - <%= cos.end.strftime('%H:%M') %>
  <%= link_to("キャンセルする", consultant_path(cos.id), method: :delete) unless cos.date < Date.current %><br>
<% end %>

app/views/pages/_user_not_logged_in.html.erb
<h1>ファイナンシャルプランナーに相談しよう!!</h1>

<%= link_to "アカウントを作成する", signup_path %>
<%= link_to "ログインする", login_path %>

app/views/pages/home.html.erb
<% if logged_in? %>
  <% if current_user.fp %>
    <%= render 'pages/fp_user_logged_in' %>
  <% else %>
    <%= render 'pages/user_logged_in' %>
  <% end %>
<% else %>
  <%= render 'pages/user_not_logged_in' %>
<% end %>

app/views/reserves/index.html.erb
<h1><%= "#{@day} (#{week @day.wday})" %></h1>
<%= link_to("前の日  #{@day - 1}", reserves_path(date: @day - 1)) unless @day == Date.current %>
<%= link_to("次の日  #{@day + 1}", reserves_path(date: @day + 1)) %><br>

<%= form_for @fp_user, url: reserves_path(date: @day), method: :post do |f| %>
  <% if @set_time %>
    <%= f.hidden_field :id_set, value: [@set_time.first.id, @set_time.last.id] %>
    <%#= f.hidden_field :id_end, @set_time.last.id.to_s %>
    <%= f.collection_check_boxes(:fp_reserf_ids, @set_time, :id, :start ) do |t| %>
      <%= t.label { t.check_box + t.text.strftime('%H:%M') + " - " + t.object.end.strftime('%H:%M') } %><br>
    <% end %>
  <% end %>
  <%= submit_tag %>
<% end %>

app/views/shared/_error.html.erb
<% if @user.errors.any? %>
  <% @user.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
<% end %>

app/views/time_settings/edit.html.erb
<%= form_tag timesettings_path, method: :patch do %>
  <table border="1" width="500" cellspacing="0" cellpadding="5" bordercolor="#000">
    <tr><th>曜日</th><th>時間間隔</th><th>開始時間</th><th>終了時間</th><th>出勤</th></tr>
  <% @time_settings.each do |setting| %>
    <%= fields_for "setting[]", setting do |set| %>
      <tr>
      <td><%= week set.object.week %></td>
      <td><%= set.number_field :interval %></td>
      <td><%= set.time_field :start %></td>
      <td><%= set.time_field :end %></td>
      <td><%= set.check_box :workday %></td>
      </tr>
    <% end %>
  <% end %>
</table>
  <%= submit_tag %>
<% end %>

app/views/users/edit.html.erb
<h1>ユーザー編集画面</h1>

<%= form_for(@user, url: edit_path) do |f| %>
  <%= render 'shared/error' %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :email %>
  <%= f.email_field :email %>
  <%= f.submit "編集する" %>
<% end %>

app/views/users/index.html.erb
<% @users.each do |user| %>
<%#= render 'shared/error' %>
  <%= form_with model: user, url: users_path do |f| %>
    Name: <%= f.text_field :name %>
    Email: <%= f.text_field :email %>
    FP user: <%= f.check_box :fp %>
    <%= submit_tag %>
  <% end %>
<% end %>

app/views/users/new.html.erb
<h1>登録画面</h1>

<%= form_for(@user, url: signup_path) do |f| %>
  <%= render 'shared/error' %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :email %>
  <%= f.email_field :email %>
  <%= f.submit "アカウントを作成する" %>
<% end %>